services:
  website:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/var/www/
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
x-dockge:
  urls:
    - https://uptime.kuma.pet
networks: {}
